name: Java CI

# Workflow triggers:
on:
  # Kör workflowen vid varje push till någon branch
  push:
    branches:
      - '*'
  # Kör workflowen vid pull requests till någon branch
  pull_request:
    branches:
      - '*'

jobs:
  build:
    # Använd den senaste versionen av Ubuntu som miljö för att köra jobben
    runs-on: ubuntu-latest

    steps:
    # Klona repot till arbetsmiljön
    - name: Checkout code
      uses: actions/checkout@v2

    # Installera JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    # Bygg projektet med Maven
    - name: Build with Maven
      run: mvn clean install

    # Kör tester
    - name: Run tests
      run: mvn test

    # Kör Checkstyle för att kontrollera kodstandarder
    - name: Run Lint (Checkstyle)
      run: mvn checkstyle:check

    # Paketera applikationen i en körbar JAR-fil (om tillämpligt)
    - name: Package the application
      run: mvn package

    # Kör den paketerade applikationen
    - name: Run the application
      run: |
        java -jar target/*.jar
